### ISSUE TITLE
Gateway implementation and proxy deployment script

### ISSUE THREAD

**Issue by sammy1991106** [axelarnetwork/axelar-cgp-solidity#70]
Since we've separated the gateway proxy and implementation deployments, core no longer can provide the exact bytecode anymore. We need a script to facilitate the deployments. Ideally, the script would be able to do the followings.
1. Deploy gateway implementation to a configured evm chain
2. Query a configured Axelar RPC node for that evm chain's master/secondary/external keys
3. Deploy gateway proxy with information from step 1 and 2
4. Output the deployed gateway proxy's address

**Comment by jcs47** [comment]
implemented in https://github.com/axelarnetwork/axelar-cgp-solidity/pull/76
